image: git01.iis.fhg.de:5005/ks-ip-lib/software/libjapi:latest

variables:
        GIT_SUBMODULE_STRATEGY: recursive

stages:
        - build
        - build_test
        - run_test
        - doc
        - build_rpm
        - publish 

job 1:
        stage: build
        script:
        - "mkdir build && cd build"
        - "cmake3 ../ 2>&1 | tee cmake.log"
        - "make 2>&1 | tee build.log"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - "build/libjapi.so"
                        - "build/libjapi-static.a"
                        - "build/cmake.log"
                        - "build/build.log"
job 2:
        stage: build_test
        script:
        - "cd build"
        - "cmake3 ../"
        - "make testsuite 2>&1 | tee build_test.log"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - "build/build_test.log"
                        - "test/*"
                        - "build/testsuite"
job 3:
        stage: run_test
        script:
        - "cd build"
        - "cmake3 ../"
        - "make run_test 2>&1 | tee run_test.log"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - "build/run_test.log"
job 4:
        stage: doc
        script:
        - "cd build"
        - "cmake3 ../"
        - "make doc 2>&1 | tee doc.log"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - "build/doc.log"
                        - "build/doc/*"
job 5:
        stage: build_rpm
        script:
        - "package/create_rpm.sh"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - "package/rpmbuild/RPMS/x86_64/libjapi*.rpm"
pages:
        stage: publish
        dependencies:
        - job 4
        - job 1
        - job 5
        script:
        - mkdir -p public
        - mkdir -p public/repo/x86_64
        - mv build/doc public
        - mv package/libjapi.repo public/repo/
        - touch public/repo/index.html
        - $(echo "<p><a href=x86_64/$(basename package/rpmbuild/RPMS/x86_64/libjapi-[0-9]*.rpm)>$(basename package/rpmbuild/RPMS/x86_64/libjapi-[0-9]*.rpm)</a></p>" >> public/repo/index.html)
        - $(echo "<p><a href=x86_64/$(basename package/rpmbuild/RPMS/x86_64/libjapi-doc*.rpm)>$(basename package/rpmbuild/RPMS/x86_64/libjapi-doc*.rpm)</a></p>" >> public/repo/index.html)
        - "cp package/rpmbuild/RPMS/x86_64/libjapi*.rpm public/repo/x86_64/"
        - createrepo public/repo/
        - yum-config-manager --add-repo public/repo/libjapi.repo
        artifacts:
                paths:
                        - public
        only:
        - master
