image: git01.iis.fhg.de:5005/ks-ip-lib/software/libjapi:latest

variables:
        GIT_SUBMODULE_STRATEGY: recursive

stages:
        - build
        - build_test
        - run_test
        - doc
        - build_rpm
        - publish 

job 1:
        stage: build
        script:
        - "make 2>&1 | tee build.log"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - "obj/*"
                        - "lib/libjapi.a"
                        - build.log
job 2:
        stage: build_test
        script:
        - "make build_test 2>&1 | tee build_test.log"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - build_test.log
                        - "testobj/*"
                        - "googletest/googletest/make/libgtest_main.a"
                        - "test/*"
                        - "testsuite"
job 3:
        stage: run_test
        script:
        - "make run_test 2>&1 | tee run_test.log"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - run_test.log
job 4:
        stage: doc
        script:
        - "make doc 2>&1 | tee doc.log"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - doc.log
                        - "doc/*"
job 5:
        stage: build_rpm
        script:
        - "package/create_rpm.sh"
        artifacts:
                when: always
                expire_in: 1 week
                paths:
                        - "package/rpmbuild/RPMS/x86_64/libjapi*.rpm"
pages:
        stage: publish
        dependencies:
        - job 4
        - job 1
        - job 5
        script:
        - mkdir -p public/$CI_COMMIT_REF_NAME
        - mkdir -p public/repo/x86_64
        - mv doc public/$CI_COMMIT_REF_NAME
        - touch public/doc.html
        - echo "<h2>Documentation</h2><br/><a href=$CI_COMMIT_REF_NAME/doc/html/index.html>"Documentation for Branch $CI_COMMIT_REF_NAME"</a>" >> public/doc.html
        - mv package/libjapi.repo public/repo/
        - touch public/repo/index.html
        - $(echo "<p><a href=x86_64/$(basename package/rpmbuild/RPMS/x86_64/libjapi-[0-9]*.rpm)>$(basename package/rpmbuild/RPMS/x86_64/libjapi-[0-9]*.rpm)</a></p>" >> public/repo/index.html)
        - $(echo "<p><a href=x86_64/$(basename package/rpmbuild/RPMS/x86_64/libjapi-doc*.rpm)>$(basename package/rpmbuild/RPMS/x86_64/libjapi-doc*.rpm)</a></p>" >> public/repo/index.html)
        - "cp package/rpmbuild/RPMS/x86_64/libjapi*.rpm public/repo/x86_64/"
        - createrepo public/repo/
        - yum-config-manager --add-repo public/repo/libjapi.repo
        artifacts:
                paths:
                        - public
