FROM centos:7
MAINTAINER Deniz Armagan <deniz.armagan@iis.fraunhofer.de>

# Install dependencies
RUN yum install -y epel-release json-c-devel gcc gcc-c++ make git rpm-build doxygen graphviz createrepo
RUN yum install -y cmake3
