FROM centos:7
MAINTAINER Deniz Armagan <deniz.armagan@iis.fraunhofer.de>

# Install dependencies
RUN yum install -y epel-release json-c-devel gcc gcc-c++ make rpm-build doxygen graphviz createrepo cmake3

